---
title: "A3: Incarceration"
output: html_document
---

### Introduction

In the United States of America we are currently facing a major problem of mass incarceration which is built off of generations and generations of systematic inequality in our criminal justice system. The United States has the highest incarceration rate in the world yet we still have high crimes or rates so there is a disconnection. People of color but in particular black people have the highest rates of incarceration. Through my analysis I hope to find some information as to what is causing these disparities. The variables I am choosing to analyze are is prison population, jail population, pretrial population, jurisdiction identifier, and race and gender. I chose prison population to further explore how many pople are in prisons in different states and counties and to look for certain trends. Jail population will allow me to see how individuals are in jail and give more insight as to what happens before trial. Pretrial population shows how many people are held in jail and for how long and this can be very insightful to see if racial sterotypes are at play. Jurisdiction Identifier can help with a new insight on the analysis because it gives us information on the jurisdictional level. Race and gender will allow us to see where the disapraties are more at play and in which locations. 

### Summary Information

For the purpose of my assignment I analyzed several different trends across jails and prisons in the United States of America. The first statistic that I calculated was the average prison population across all of the prisons in America and I found that the number was 617 people. This gives a good idea as to how many people are incarcerated and you might think this number will be smaller or larger in different parts of the country due to population size but it is still very high considering it takes into account every single prison in the country. The second statistic that I calculated was which state and county had the highest prison population. Los Angeles County in California has the highest population with 58,068 people incarcerated where 54,365 of them are male and 3,703 are female. The third statistic that I calculated was which state and county had the lowest prison population. Alpine County in California had the lowest numbers as they had 0 people in jail which makes sense because the total population of this rural county is 1,120 people. It is quite interesting to see how the same state can have such different numbers. The fourth statistic that I calculated was to see the change in prison population in Washington state over the last ten years. In King County there was surprisingly a 13.6% decrease in incarceration rates but Snohomish County had a 12.4% increase. The largest difference was in San Juan County with a decrease of 55.6% in incarceration rates. The last statistic that I calculated was the distribution of prison population by race across Washington State. AAPI population was 1.649264%, Black population was 27.38535%, LatinX population was 9.057946%, Native population was 3.699751%, White population was 55.56665 and other races was 2.64104%. 

### The Dataset

The data was collected by the Vera Institute of Justice. They collected the data by two Bureau of Justice Statistics. One of them being the Census of Jails and the Annual Survey of Jails. The Census of Jails is gathering information from every jail in the United States of America every five to eight years whereas the Annual Survey of Jails is only able to cover one third of the jails. The data was collected because it is a very important topic that needs to have more light shed on to show the injustices that are happening. Mass incarceration is an epidemic in the United States of America and more information on it needs to be provided to help facilitate change for our generations and more to come. The amount of observations in the dataset across all five smaller datasets that we are working with is 454,594. The amount of features that are in my data are 133 but this is across all five smaller datasets that we received so it is to be noted that a lot of them are overlapping. An ethical question or questions of power we need to consider while working with this data is to not fall under preconceived notions we might have and to retain privacy of these individuals. A possible limitation or problem with this data might be that the data collection might be inaccurate due to different jurisdictions and that certain systematic biases are in play since they're already built into the system.  

### Trends Over Time Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The first chart that you will create and include will show the trend over time of your variable/topic. Think carefully about what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Show more than one, but fewer than ~10 trends
  - This may mean showing the same measure for different locations or different racial groups. Think carefully about a meaningful comparison of locations (e.g., the top 10 counties in a state, top 10 states, etc.)
- You must have clear x and y axis labels
- The chart needs a clear title 
- You need a legend for your different line colors and a clear legend title

When we say "clear" or "human readable" titles and labels, that means that you should not just display the variable name.

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Variable Comparison Chart

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The second chart that you will create and include will show how two different (continuous) variables are related to one another. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- You must have clear x and y axis labels
- The chart needs a clear title 
- If you choose to add a color encoding (not required), you need a legend for your different color and a clear legend title

### Map

Include a chart. Make sure to describe why you included the chart, and what patterns emerged

The last chart that you will create and include will show how a variable is distributed geographically. Again, think carefully about what such a comparison means and what you want to communicate to your user (you may have to find relevant trends in the dataset first!). Here are some requirements to help guide your design:

- Your map needs a title
- Your color scale needs a legend with a clear label
- Use a map based coordinate system to set the aspect ratio of your map

